from flask import Flask, render_template, request

app = Flask(__name__)

universities = [
    {
        'name': 'Algoma University', 
        'location': 'Sault Ste. Marie and Brampton, Ontario, Canada', 
        'image': 'https://images.shiksha.com/mediadata/images/1541063462php7PDvWb.jpeg',
        'program_overview': 'The Computer Science major at Algoma University aims to equip students with the knowledge and skills required for a career in the field of computer science. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, database systems, computer networks, artificial intelligence, and more.',
        'degree_options': 'Algoma University offers a Bachelor of Science (B.Sc.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'Algoma University provides co-operative education (co-op) opportunities for students in the Computer Science program. Co-op programs allow students to gain valuable work experience in the industry while pursuing their studies. Co-op placements are typically paid and provide students with the chance to apply their theoretical knowledge in real-world settings.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s best to check with Algoma University\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in relevant subjects such as mathematics and science.',
        'program_structure': 'The Computer Science major at Algoma University follows a structured curriculum that includes a combination of core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to take courses in programming, data structures, algorithms, software engineering, computer networks, databases, and more.',
        'research_opportunities': 'Algoma University offers research opportunities for Computer Science students, allowing them to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research opportunities may include areas such as artificial intelligence, data science, cybersecurity, and software development.',
        'facilities_and_resources': 'Algoma University provides various facilities and resources to support Computer Science students. This includes computer labs equipped with the necessary software and hardware for programming and experimentation. The university also offers access to libraries, online databases, and other learning resources to aid in research and study.',
        'career_prospects': 'A degree in Computer Science from Algoma University can lead to diverse career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, database administrator, cybersecurity specialist, data scientist, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in various sectors, including software development companies, tech startups, government organizations, and research institutions.'
    },
    {
        'name': 'Brock University', 
        'location': 'St. Catharines, Ontario, Canada', 
        'image': 'https://brocku.ca/campus-safety/wp-content/uploads/sites/80/csscarousel3-1800x1100.jpg?x42659', 
        'program_overview': 'The Computer Science major at Brock University is designed to prepare students for careers in the field of computer science and related areas. The program covers core topics such as programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, and more. Students gain a strong theoretical understanding along with practical skills to develop software applications and solve complex computational problems.',
        'degree_options': 'Brock University offers a Bachelor of Science (B.Sc.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'Brock University provides co-operative education (co-op) opportunities for Computer Science students. The co-op program allows students to gain valuable work experience in the industry, alternating work terms with academic terms. Co-op placements are typically paid and provide students with hands-on experience, networking opportunities, and the chance to apply their knowledge in real-world settings.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with Brock University\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in relevant subjects such as mathematics and science.',
        'program_structure': 'The Computer Science major at Brock University follows a structured curriculum that includes core computer science courses and elective courses. The program covers fundamental topics in computer science and provides opportunities for specialization through elective courses. Students can expect to study areas such as programming, algorithms, data structures, software development methodologies, computer architecture, operating systems, and more.',
        'research_opportunities': 'Brock University offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can collaborate with faculty members on ongoing research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, and more.',
        'facilities_and_resources': 'Brock University provides modern facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research endeavors.',
        'career_prospects': 'A degree in Computer Science from Brock University can lead to various career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in sectors such as software development companies, technology consulting firms, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'Carleton University', 
        'location': 'Ottawa, Ontario, Canada', 
        'image': 'https://th.bing.com/th/id/OIP.jC0Sd4vnK-iE3OCYf8Tf_QHaE6?w=254&h=180&c=7&r=0&o=5&dpr=2&pid=1.7', 
        'program_overview': 'Carleton University\'s Computer Science major program focuses on providing students with a strong foundation in computer science theory and practical skills. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, artificial intelligence, computer networks, databases, and more. Students gain the necessary knowledge and skills to solve complex computational problems and develop innovative software solutions.',
        'degree_options': 'Carleton University offers a Bachelor of Computer Science (B.Comp.Sc.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'Carleton University provides co-operative education (co-op) opportunities for Computer Science students. The co-op program integrates periods of work experience with academic terms, allowing students to gain practical industry experience. Co-op placements are typically paid and provide students with valuable networking opportunities and exposure to real-world projects and challenges.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with Carleton University\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This typically includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major at Carleton University follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming, data structures, algorithms, software development methodologies, computer architecture, operating systems, and more.',
        'research_opportunities': 'Carleton University offers extensive research opportunities for Computer Science students. Students can work with faculty members on research projects, contribute to ongoing research initiatives, or pursue independent research under the guidance of experienced researchers. Research areas may include artificial intelligence, machine learning, data science, software engineering, cybersecurity, and more.',
        'facilities_and_resources': 'Carleton University provides state-of-the-art facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and collaborative spaces to facilitate their studies and research endeavors.',
        'career_prospects': 'A degree in Computer Science from Carleton University can open up diverse career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in various sectors, including software development companies, technology consulting firms, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'University of Guelph', 
        'location': 'Guelph, Ontario, Canada', 
        'image': 'https://www.wur.nl/upload/c7d8c63a-e6c0-4a96-9ea8-a895248cc708_shutterstock_1202155618.jpg', 
        'program_overview': 'The Computer Science major program at the University of Guelph focuses on providing students with a strong foundation in computer science principles, theories, and practical skills. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, and more. Students gain the necessary knowledge and skills to develop software solutions and analyze complex computational problems.',
        'degree_options': 'The University of Guelph offers a Bachelor of Computing (B.Comp.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'The University of Guelph provides co-operative education (co-op) opportunities for Computer Science students. The co-op program integrates periods of work experience with academic terms, allowing students to gain valuable industry experience and make professional connections. Co-op placements are typically paid and offer students the chance to apply their knowledge in real-world settings.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with the University of Guelph\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at the University of Guelph follows a structured curriculum that includes core computer science courses and elective courses. The program covers fundamental topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer graphics, artificial intelligence, databases, and more.',
        'research_opportunities': 'The University of Guelph offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can collaborate with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, cybersecurity, human-computer interaction, software engineering, and more.',
        'facilities_and_resources': 'The University of Guelph provides modern facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from the University of Guelph can lead to various career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in sectors such as software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'Toronto Guelph - Humber', 
        'location': 'Toronto, Ontario, Canada', 
        'image': 'https://www.ontariouniversitiesinfo.ca/assets/files/images/ouac_ghbuilding_2426.jpg', 
        'program_overview': 'The Computer Science major program at Toronto Guelph-Humber focuses on providing students with a solid foundation in computer science principles, theories, and practical skills. The program covers a range of topics, including programming, algorithms, data structures, software engineering, computer networks, databases, and more. Students acquire the knowledge and skills necessary to design and develop software applications and solve computational problems.',
        'degree_options': 'Toronto Guelph-Humber offers an Honours Bachelor of Applied Science (BASc) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'Toronto Guelph-Humber provides co-operative education (co-op) opportunities for Computer Science students. The co-op program allows students to gain practical work experience in the industry while pursuing their studies. Co-op placements are typically paid and provide students with valuable professional experience, networking opportunities, and exposure to real-world projects.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with Toronto Guelph-Humber\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the institution. This typically includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at Toronto Guelph-Humber follows a structured curriculum that includes core computer science courses and elective courses. The program covers fundamental topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, databases, computer networks, and more.',
        'research_opportunities': 'Toronto Guelph-Humber offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can collaborate with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software development, cybersecurity, and more.',
        'facilities_and_resources': 'Toronto Guelph-Humber provides modern facilities and resources to support Computer Science students. The institution has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'Graduates from the Computer Science major program at Toronto Guelph-Humber can pursue various career prospects in the technology industry. They may seek roles such as software developer, systems analyst, database administrator, cybersecurity specialist, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in sectors such as software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'Lakehead University', 
        'location': 'Toronto, Ontario, Canada', 
        'image': 'https://www.britishacademiccenter.com/wp-content/uploads/2020/06/lakehead-university.jpg', 
        'program_overview': 'The Computer Science major program at Lakehead University focuses on equipping students with the knowledge and skills needed for a career in the field of computer science. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, databases, computer networks, artificial intelligence, and more. Students develop a strong understanding of computer science principles and gain hands-on experience through practical projects.',
        'degree_options': 'Lakehead University offers a Bachelor of Science (B.Sc.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'Lakehead University provides co-operative education (co-op) opportunities for Computer Science students. The co-op program integrates periods of work experience with academic terms, allowing students to gain valuable industry experience. Co-op placements are typically paid and provide students with the opportunity to apply their knowledge and skills in real-world settings.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with Lakehead University\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at Lakehead University follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'Lakehead University offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, and more.',
        'facilities_and_resources': 'Lakehead University provides modern facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from Lakehead University can lead to various career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in sectors such as software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'Laurentian University', 
        'location': 'Sudbury, Ontario, Canada', 
        'image': 'https://macleans.ca/wp-content/uploads/2018/10/MAC55_MBA_M_LAURENTIAN01-copy.jpg', 
        'program_overview': 'The Computer Science major program at Laurentian University focuses on preparing students for a career in the field of computer science. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, databases, computer networks, artificial intelligence, and more. Students develop a deep understanding of computer science concepts and gain practical experience through hands-on projects.',
        'degree_options': 'Laurentian University offers a Bachelor of Computer Science (B.Comp.Sc.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'Laurentian University provides co-operative education (co-op) opportunities for Computer Science students. The co-op program integrates work experience with academic terms, allowing students to gain valuable industry experience. Co-op placements are typically paid and provide students with the opportunity to apply their knowledge and skills in real-world settings.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with Laurentian University\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at Laurentian University follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'Laurentian University offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, and more.',
        'facilities_and_resources': 'Laurentian University provides modern facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from Laurentian University can lead to various career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in sectors such as software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'McMaster University', 
        'location': 'Hamilton, Ontario, Canada', 
        'image': 'https://cdn.britannica.com/13/153913-050-8B44F7C6/Hamilton-Hall-McMaster-University-Canada-Ontario.jpg', 
        'program_overview': 'The Computer Science major program at McMaster University aims to equip students with the knowledge and skills necessary for a successful career in computer science. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, databases, computer networks, artificial intelligence, and more. Students gain a deep understanding of computer science principles and develop problem-solving and critical thinking abilities.',
        'degree_options': 'McMaster University offers a Bachelor of Science (B.Sc.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'McMaster University provides co-operative education (co-op) opportunities for Computer Science students. The co-op program allows students to gain practical work experience in the industry while pursuing their studies. Co-op placements are typically paid and provide students with the opportunity to apply their knowledge and skills in real-world settings.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with McMaster University\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at McMaster University follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'McMaster University offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, human-computer interaction, and more.',
        'facilities_and_resources': 'McMaster University provides state-of-the-art facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from McMaster University can lead to diverse and promising career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in sectors such as software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'Ontario Tech University', 
        'location': 'Oshawa, Ontario, Canada', 
        'image': 'https://news.ontariotechu.ca/archives/2022/03/images/vpri-young-university-top-200-thumbnail.jpg', 
        'program_overview': 'The Computer Science major program at Ontario Tech University focuses on preparing students for a wide range of careers in the field of computer science. The program covers a variety of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, cybersecurity, and more. Students acquire a strong theoretical understanding and practical skills necessary for designing and developing software applications.',
        'degree_options': 'Ontario Tech University offers a Bachelor of Science (B.Sc.) degree with a major in Computer Science. Additionally, the university offers various specialized streams and options within the Computer Science program, such as Artificial Intelligence, Computer Game Development, Cybersecurity, and Data Science. These options allow students to tailor their studies and focus on specific areas of interest within computer science.',
        'coop_option': 'Ontario Tech University provides co-operative education (co-op) opportunities for Computer Science students. The co-op program integrates work terms with academic terms, allowing students to gain valuable work experience in the industry. Co-op placements are typically paid and provide students with opportunities to apply their knowledge in real-world settings, develop professional skills, and make industry connections.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with Ontario Tech University\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at Ontario Tech University follows a structured curriculum that includes core computer science courses, specialized courses based on the chosen stream, and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more',
        'research_opportunities': 'Ontario Tech University offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work with faculty members on research projects, contribute to ongoing research initiatives, or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, human-computer interaction, and more.',
        'facilities_and_resources': 'Ontario Tech University provides state-of-the-art facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and collaborative spaces to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from Ontario Tech University can lead to diverse and promising career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in various sectors, including software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'University of Ottawa', 
        'location': 'Ottawa, Ontario, Canada', 
        'image': 'https://www.ontariouniversitiesinfo.ca/assets/files/images/universityEventImageNew_20150909-bf-campus-sunset-22_rs2.jpg', 
        'program_overview': 'The Computer Science major program at the University of Ottawa focuses on providing students with a solid foundation in computer science theory, practical skills, and problem-solving techniques. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, and more. Students gain a deep understanding of computer science principles and develop the skills necessary to design and develop innovative software solutions.',
        'degree_options': 'The University of Ottawa offers a Bachelor of Computer Science (B.CS.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'The University of Ottawa provides co-operative education (co-op) opportunities for Computer Science students. The co-op program integrates work experience with academic terms, allowing students to gain practical industry experience. Co-op placements are typically paid and provide students with opportunities to apply their knowledge in real-world settings, develop professional skills, and establish valuable industry connections.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with the University of Ottawa\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at the University of Ottawa follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'The University of Ottawa offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, human-computer interaction, and more.',
        'facilities_and_resources': 'The University of Ottawa provides modern facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from the University of Ottawa can lead to diverse and promising career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in sectors such as software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'Queen\'s University', 
        'location': 'Kingston, Ontario, Canada', 
        'image': 'https://www.queensu.ca/gazette/sites/default/files/assets/1000x667%20-%20opt%204.jpg', 
        'program_overview': 'The Computer Science major program at Queen\'s University focuses on providing students with a strong foundation in computer science theory, practical skills, and problem-solving abilities. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, and more. Students gain in-depth knowledge and critical thinking skills necessary for designing and developing innovative software solutions.',
        'degree_options': 'Queen\'s University offers a Bachelor of Computing (B.Comp.) degree with a major in Computer Science. Additionally, students may have the option to pursue a Bachelor of Computing Honours (B.Comp.Hons.) degree, which typically involves a more intensive research component. The program usually takes four years to complete on a full-time basis.',
        'coop_option': 'Queen\'s University offers co-operative education (co-op) opportunities for Computer Science students through its Engineering and Applied Science Co-op program. Co-op placements allow students to gain practical work experience in the industry, alternating work terms with academic terms. Co-op placements are typically paid and provide students with hands-on experience, networking opportunities, and the chance to apply their knowledge in real-world settings.',
        'admission_requirements': 'Specific admission requirements may vary, so it\'s recommended to check with Queen\'s University\'s admissions department for the most up-to-date information. Generally, to be eligible for the Computer Science major program, applicants need to meet the minimum academic requirements set by the university. This usually includes a high school diploma or equivalent with satisfactory grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at Queen\'s University follows a structured curriculum that includes core computer science courses and elective courses. The program covers fundamental topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'Queen\'s University offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, human-computer interaction, and more.',
        'facilities_and_resources': 'Queen\'s University provides state-of-the-art facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from Queen\'s University can lead to diverse and promising career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in various sectors, including software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'University of Toronto', 
        'location': 'Toronto, Ontario, Canada', 
        'image': 'https://cdn.britannica.com/62/127362-050-CECE8AFE/Main-Hall-Trinity-College-University-of-Toronto.jpg', 
        'program_overview': 'The Computer Science major program at the University of Toronto focuses on providing students with a strong foundation in computer science theory, practical skills, and problem-solving abilities. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, and more. Students gain in-depth knowledge and critical thinking skills necessary for designing and developing innovative software solutions.',
        'degree_options': 'The University of Toronto offers several degree options for Computer Science, including a Bachelor of Science (B.Sc.) degree with a major in Computer Science, a Bachelor of Applied Science (B.A.Sc.) degree with a major in Computer Engineering (a program combining elements of computer science and electrical engineering), and a combined Computer Science and Mathematics program. The program typically takes four years to complete on a full-time basis.',
        'coop_option': 'The University of Toronto provides co-operative education (co-op) opportunities for Computer Science students through its Professional Experience Year Co-op Program. Co-op placements allow students to gain valuable work experience in the industry, alternating work terms with academic terms. Co-op placements are typically paid and provide students with hands-on experience, networking opportunities, and the chance to apply their knowledge in real-world settings.',
        'admission_requirements': 'Admission to the Computer Science major program at the University of Toronto is highly competitive. Specific admission requirements may vary, so it\'s recommended to check with the university\'s admissions department for the most up-to-date information. Generally, to be eligible, applicants need to meet the minimum academic requirements set by the university. This typically includes a high school diploma or equivalent with strong grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at the University of Toronto follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'The University of Toronto offers extensive research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, human-computer interaction, and more.',
        'facilities_and_resources': 'The University of Toronto provides state-of-the-art facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from the University of Toronto can lead to diverse and promising career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in various sectors, including software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'University of Toronto Scarborough', 
        'location': 'Scarborough, Ontario, Canada', 
        'image': 'https://assets.simpleviewinc.com/simpleview/image/upload/crm/toronto/UTSC_29059-112045_99C8776B-5056-A36F-23923C9D7F161E0E-99c873c95056a36_99c88159-5056-a36f-239adaeb86e3d045.jpg', 
        'program_overview': 'The Computer Science major program at the University of Toronto Scarborough focuses on providing students with a thorough understanding of computer science principles and applications. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, and more. Students gain critical thinking skills, collaborative abilities, and the knowledge needed to design and develop innovative software solutions.',
        'degree_options': 'The University of Toronto Scarborough offers a Bachelor of Science (B.Sc.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'The University of Toronto Scarborough provides co-operative education (co-op) opportunities for Computer Science students through its Co-op Programs. Co-op placements allow students to gain valuable work experience in the industry, alternating work terms with academic terms. Co-op placements are typically paid and provide students with hands-on experience, networking opportunities, and the chance to apply their knowledge in real-world settings.',
        'admission_requirements': 'Admission to the Computer Science major program at the University of Toronto Scarborough is highly competitive. Specific admission requirements may vary, so it\'s recommended to check with the university\'s admissions department for the most up-to-date information. Generally, to be eligible, applicants need to meet the minimum academic requirements set by the university. This typically includes a high school diploma or equivalent with strong grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at the University of Toronto Scarborough follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'The University of Toronto Scarborough offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, human-computer interaction, and more.',
        'facilities_and_resources': 'The University of Toronto Scarborough provides state-of-the-art facilities and resources to support Computer Science students. The campus has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from the University of Toronto Scarborough can lead to diverse and promising career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in various sectors, including software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'University of Toronto Mississauga', 
        'location': 'Mississauga, Ontario, Canada', 
        'image': 'https://upload.wikimedia.org/wikipedia/commons/d/de/UTM-Library.jpg', 
        'program_overview': 'The Computer Science major program at the University of Toronto Mississauga focuses on providing students with a solid understanding of computer science principles and their applications. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, and more. Students develop critical thinking skills, collaborative abilities, and the knowledge necessary to design and develop innovative software solutions.',
        'degree_options': 'The University of Toronto Mississauga offers a Bachelor of Science (B.Sc.) degree with a major in Computer Science. This undergraduate program typically takes four years to complete on a full-time basis.',
        'coop_option': 'The University of Toronto Mississauga provides co-operative education (co-op) opportunities for Computer Science students through its UTM Co-op Program. Co-op placements allow students to gain valuable work experience in the industry, alternating work terms with academic terms. Co-op placements are typically paid and provide students with hands-on experience, networking opportunities, and the chance to apply their knowledge in real-world settings.',
        'admission_requirements': 'Admission to the Computer Science major program at the University of Toronto Mississauga is highly competitive. Specific admission requirements may vary, so it\'s recommended to check with the university\'s admissions department for the most up-to-date information. Generally, to be eligible, applicants need to meet the minimum academic requirements set by the university. This typically includes a high school diploma or equivalent with strong grades in mathematics and science-related subjects.',
        'program_structure': 'The Computer Science major program at the University of Toronto Mississauga follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'The University of Toronto Mississauga offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, human-computer interaction, and more.',
        'facilities_and_resources': 'The University of Toronto Mississauga provides state-of-the-art facilities and resources to support Computer Science students. The campus has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from the University of Toronto Mississauga can lead to diverse and promising career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in various sectors, including software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
    {
        'name': 'University of Waterloo', 
        'location': 'Waterloo, Ontario, Canada', 
        'image': 'https://www.brocksolutions.com/wp-content/uploads/2020/02/University-of-Waterloo.jpg', 
        'program_overview': 'The Computer Science major program at the University of Waterloo focuses on providing students with a solid foundation in computer science theory, practical skills, and problem-solving abilities. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, and more. Students develop critical thinking skills and gain hands-on experience through challenging projects and cooperative work terms.',
        'degree_options': 'The University of Waterloo offers a Bachelor of Computer Science (B.CS.) degree with a major in Computer Science. Additionally, students can pursue specialized degree options such as the Bachelor of Computer Science (B.CS.) - Data Science option, Bachelor of Computer Science (B.CS.) - Bioinformatics option, or Bachelor of Computer Science (B.CS.) - Digital Hardware option. These options allow students to tailor their studies to specific areas of interest within computer science.',
        'coop_option': 'The University of Waterloo is known for its co-operative education (co-op) program, which provides students with extensive work experience in their field of study. The CS program offers co-op opportunities, allowing students to alternate between academic terms and paid work terms in relevant industry positions. Co-op placements provide valuable real-world experience, networking opportunities, and a chance to apply classroom knowledge in professional settings.',
        'admission_requirements': 'Admission to the Computer Science major program at the University of Waterloo is highly competitive. Specific admission requirements may vary, so it\'s recommended to check with the university\'s admissions department for the most up-to-date information. Generally, successful applicants demonstrate strong academic performance, particularly in mathematics and science-related subjects. Meeting the minimum requirements does not guarantee admission due to the competitive nature of the program.',
        'program_structure': 'The Computer Science major program at the University of Waterloo follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'The University of Waterloo offers numerous research opportunities for Computer Science students to engage in cutting-edge research projects. Students can work closely with faculty members on research initiatives or pursue independent research under their guidance. Research areas in computer science at Waterloo include artificial intelligence, data science, cybersecurity, human-computer interaction, software engineering, and more.',
        'facilities_and_resources': 'The University of Waterloo provides state-of-the-art facilities and resources to support Computer Science students. The campus has dedicated computer labs equipped with the necessary software and hardware for programming, research, and experimentation. Additionally, students have access to libraries, online databases, research centers, collaboration spaces, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from the University of Waterloo opens up numerous career prospects in the technology industry. Graduates are highly sought after by employers and can pursue roles such as software developer, data scientist, systems analyst, cybersecurity analyst, network administrator, and more. The University of Waterloo\'s strong reputation in the tech industry, combined with the co-op experience gained during the program, provides graduates with excellent job prospects and opportunities for career advancement.'
    },
    {
        'name': 'Western University', 
        'location': 'London, Ontario, Canada', 
        'image': 'https://www.ontariouniversitiesinfo.ca/assets/files/images/uc_c_1080x700.jpg', 
        'program_overview': 'The Computer Science major program at Western University focuses on providing students with a strong foundation in computer science theory, practical skills, and problem-solving abilities. The program covers a wide range of topics, including programming, algorithms, data structures, software engineering, computer networks, artificial intelligence, databases, and more. Students develop critical thinking skills, collaborative abilities, and the knowledge needed to design and develop innovative software solutions.',
        'degree_options': 'Western University offers a Bachelor of Science (B.Sc.) degree with a major in Computer Science. Additionally, the university offers a combined program in Computer Science and Software Engineering (B.Sc. in Computer Science and Software Engineering). This program combines elements of both disciplines and provides students with a broader skill set. The program typically takes four years to complete on a full-time basis.',
        'coop_option': 'Western University provides co-operative education (co-op) opportunities for Computer Science students through its Western Co-operative Education (WACE) program. Co-op placements allow students to gain valuable work experience in the industry, alternating work terms with academic terms. Co-op placements are typically paid and provide students with hands-on experience, networking opportunities, and the chance to apply their knowledge in real-world settings.',
        'admission_requirements': 'Admission to the Computer Science major program at Western University is competitive. Specific admission requirements may vary, so it\'s recommended to check with the university\'s admissions department for the most up-to-date information. Generally, successful applicants demonstrate strong academic performance, particularly in mathematics and science-related subjects. Meeting the minimum requirements does not guarantee admission due to the competitive nature of the program.',
        'program_structure': 'The Computer Science major program at Western University follows a structured curriculum that includes core computer science courses and elective courses. The program covers foundational topics in computer science and allows students to specialize in areas of interest through elective courses. Students can expect to study subjects such as programming languages, algorithms, data structures, software engineering, computer architecture, operating systems, and more.',
        'research_opportunities': 'Western University offers research opportunities for Computer Science students to engage in academic research and contribute to the field. Students can work closely with faculty members on research projects or pursue independent research under their guidance. Research areas may include artificial intelligence, data science, software engineering, cybersecurity, human-computer interaction, and more.',
        'facilities_and_resources': 'Western University provides modern facilities and resources to support Computer Science students. The university has dedicated computer labs equipped with the necessary software and hardware for programming and experimentation. Additionally, students have access to libraries, online databases, research centers, and other resources to support their studies and research activities.',
        'career_prospects': 'A degree in Computer Science from Western University can lead to diverse and promising career prospects in the technology industry. Graduates may pursue roles such as software developer, systems analyst, data scientist, cybersecurity analyst, network administrator, and more. The demand for computer science professionals is high, and graduates can find employment opportunities in various sectors, including software development companies, tech startups, government organizations, research institutions, and other industries that rely on technology-driven solutions.'
    },
]

@app.route('/')
def home():
    return render_template('home.html', universities=universities)

@app.route('/university', methods=['POST'])
def university():
    university_name = request.form.get('university')
    for university in universities:
        if university['name'].lower() == university_name.lower():
            return render_template('university.html', university=university)
    return render_template('home.html', universities=universities, error="University not found")

if __name__ == '__main__':
    app.run(debug=True)
